### ISSUE TITLE
Error trying to use kindlegen on mac

### ISSUE THREAD

**Issue by benneluke** [pavelzw/calibre-kindle-comics#1]
I downloaded kindlegen file for mac. Unzipped "output" file, copied it in, and re-zipped it. 
when I try to add it to calibre i get the following error:

calibre, version 5.7.2
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '/Users/marketing/Desktop/calibre_kindle_comics/Kindle Comics Output.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.7.2  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Kindle Comics Input (0, 0, 2)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "calibre/customize/ui.py", line 472, in add_plugin
  File "calibre/customize/ui.py", line 61, in load_plugin
  File "calibre/customize/zipplugin.py", line 284, in load
  File "calibre/customize/zipplugin.py", line 379, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/Users/marketing/Desktop/calibre_kindle_comics/Kindle Comics Output.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by pavelzw** [comment]
Hi, 
it sounds like you didn't zip the file correctly. When you open your rezipped file, are you seeing a "Kindle Comics Output" Folder? If yes, that's your problem. On the main level of the zip file you need the `__init__.py` (and the other three files).
You could just try to add the `kindlegen` file to the old zip, you don't need to unzip and rezip the `Kindle Comics Output.zip`.
