### ISSUE TITLE
Conversion error

### ISSUE THREAD

**Issue by ali-oem** [pavelzw/calibre-kindle-comics#8]
calibre, version 5.22.1 (linux, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (Le choix)

Convert book 1 of 1 (Le choix)
Integration status: True
Conversion options changed from defaults:
  page_breaks_before: None
  disable_font_rescaling: True
  verbose: 2
  change_justification: 'left'
  chapter: None
  read_metadata_from_opf: '/tmp/calibre_5.22.1_tmp_us47c3m7/23wbab_6.opf'
  margin_left: 0.0
  cover: '/tmp/calibre_5.22.1_tmp_us47c3m7/lr5074wc.jpeg'
  margin_bottom: 0.0
  margin_top: 0.0
  margin_right: 0.0
  output_profile: 'kindle_pw3'
Resolved conversion options
calibre version: 5.22.1
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'left',
 'chapter': None,
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': '/tmp/calibre_5.22.1_tmp_us47c3m7/lr5074wc.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': True,
 'dont_compress': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'gamma': '1.0',
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x7f19e96ee160>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'manga': False,
 'margin_bottom': 0.0,
 'margin_left': 0.0,
 'margin_right': 0.0,
 'margin_top': 0.0,
 'margins': 'auto',
 'markup_chapter_headings': True,
 'max_height': '1680',
 'max_toc_links': 50,
 'max_width': '1264',
 'minimum_line_height': 120.0,
 'mobi_file_type': 'old',
 'mobi_ignore_margins': False,
 'mobi_keep_original_images': False,
 'mobi_toc_at_start': False,
 'no_chapters_in_toc': False,
 'no_greyscale': False,
 'no_inline_navbars': True,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x7f19e96ee4f0>,
 'page_breaks_before': None,
 'personal_doc': '[PDOC]',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': '/tmp/calibre_5.22.1_tmp_us47c3m7/23wbab_6.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2,
 'webtoon': False}
InputFormatPlugin: Kindle Comics Input running
on /tmp/calibre_5.22.1_tmp_us47c3m7/32xcnp0h.cbz
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 45, in <module>
  File "site.py", line 41, in main
  File "calibre/utils/ipc/worker.py", line 216, in main
  File "calibre/gui2/convert/gui_conversion.py", line 41, in gui_convert_override
  File "calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
  File "calibre/ebooks/conversion/plumber.py", line 1105, in run
  File "calibre/customize/conversion.py", line 245, in __call__
  File "calibre_plugins.kindle_comics.__init__", line 41, in convert
  File "calibre_plugins.kindle_comics.make_book", line 28, in make_book
  File "calibre_plugins.kindle_comics.make_book", line 50, in sanitize_tree
  File "calibre_plugins.kindle_comics.make_book", line 73, in _slugify
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.kindle_comics.kindle_comic_lib.__init__", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.kindle_comics.kindle_comic_lib.slugify", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.kindle_comics.kindle_comic_lib.text_unidecode.__init__", line 15, in <module>
  File "zipfile.py", line 1251, in __init__
NotADirectoryError: [Errno 20] Not a directory: '/home/ali/.config/calibre/plugins/Kindle Comics Input.zip/kindle_comic_lib/text_unidecode/../..'
{'manga': False, 'webtoon': False, 'margins': 'auto', 'no_greyscale': False, 'max_width': 1264, 'max_height': 1680, 'black_borders': False, 'white_borders': False, 'bordersColor': None, 'profileData': ('Kindle Paperwhite 3/4/Voyage/Oasis', (1264, 1680), [0, 0, 0, 17, 17, 17, 34, 34, 34, 51, 51, 51, 68, 68, 68, 85, 85, 85, 102, 102, 102, 119, 119, 119, 136, 136, 136, 153, 153, 153, 170, 170, 170, 187, 187, 187, 204, 204, 204, 221, 221, 221, 238, 238, 238, 255, 255, 255], 1.8), 'profile': 'KV', 'hq': False, 'forcecolor': False, 'forcepng': False, 'gamma': 1.0, 'stretch': False, 'kfx': False, 'upscale': False, 'format': 'MOBI', 'cropping': 2, 'croppingp': 1.0, 'splitter': 0, 'iskindle': True, 'panelview': True, 'covers': [], 'autoscale': False, 'righttoleft': False, 'summary': '', 'authors': ['unknown'], 'chapters': False, 'batchsplit': 1, 'customheight': 0, 'customwidth': 0, 'output': None, 'title': 'defaulttitle'}
Extracting images.
Extracted images into /tmp/calibre_5.22.1_tmp_us47c3m7/koybr02l_comic_extract
Moved images to structure in /tmp/calibre_5.22.1_tmp_us47c3m7/q917a9o1_oebps
Processing images.
Processing fileChoix-061.jpg
Processing fileChoix-005.jpg
Processing fileChoix-030.jpg
Processing fileChoix-070.jpg
Processing fileChoix-073.jpg
Processing fileChoix-069.jpg
Processing fileChoix-107.jpg
Processing fileChoix-057.jpg
Processing fileChoix-035.jpg
Processing fileChoix-018.jpg
Processing fileChoix-033.jpg
Processing fileChoix-101.jpg
Processing fileChoix-120.jpg
Processing fileChoix-116.jpg
Processing fileChoix-040.jpg
Processing fileChoix-045.jpg
Processing fileChoix-121.jpg
Processing fileChoix-094.jpg
Processing fileChoix-059.jpg
Processing fileChoix-015.jpg
Processing fileChoix-093.jpg
Processing fileChoix-037.jpg
Processing fileChoix-080.jpg
Processing fileChoix-054.jpg
Processing fileChoix-091.jpg
Processing fileChoix-074.jpg
Processing fileChoix-049.jpg
Processing fileChoix-079.jpg
Processing fileChoix-110.jpg
Processing fileChoix-050.jpg
Processing fileChoix-082.jpg
Processing fileChoix-100.jpg
Processing fileChoix-014.jpg
Processing fileChoix-034.jpg
Processing fileChoix-113.jpg
Processing fileChoix-016.jpg
Processing fileChoix-062.jpg
Processing fileChoix-017.jpg
Processing fileChoix-026.jpg
Processing fileChoix-122.jpg
Processing fileChoix-096.jpg
Processing fileChoix-039.jpg
Processing fileChoix-041.jpg
Processing fileChoix-072.jpg
Processing fileChoix-002.jpg
Processing fileChoix-019.jpg
Processing fileChoix-104.jpg
Processing fileChoix-065.jpg
Processing fileChoix-102.jpg
Processing fileChoix-012.jpg
Processing fileChoix-112.jpg
Processing fileChoix-108.jpg
Processing fileChoix-042.jpg
Processing fileChoix-088.jpg
Processing fileChoix-097.jpg
Processing fileChoix-064.jpg
Processing fileChoix-044.jpg
Processing fileChoix-052.jpg
Processing fileChoix-020.jpg
Processing fileChoix-075.jpg
Processing fileChoix-067.jpg
Processing fileChoix-077.jpg
Processing fileChoix-083.jpg
Processing fileChoix-004.jpg
Processing fileChoix-103.jpg
Processing fileChoix-071.jpg
Processing fileChoix-022.jpg
Processing fileChoix-025.jpg
Processing fileChoix-047.jpg
Processing fileChoix-058.jpg
Processing fileChoix-003.jpg
Processing fileChoix-098.jpg
Processing fileChoix-115.jpg
Processing fileChoix-028.jpg
Processing fileChoix-092.jpg
Processing fileChoix-051.jpg
Processing fileChoix-007.jpg
Processing fileChoix-105.jpg
Processing fileChoix-031.jpg
Processing fileChoix-048.jpg
Processing fileChoix-006.jpg
Processing fileChoix-066.jpg
Processing fileChoix-029.jpg
Processing fileChoix-119.jpg
Processing fileChoix-085.jpg
Processing fileChoix-068.jpg
Processing fileChoix-038.jpg
Processing fileChoix-008.jpg
Processing fileChoix-032.jpg
Processing fileChoix-114.jpg
Processing fileChoix-036.jpg
Processing fileChoix-053.jpg
Processing fileChoix-076.jpg
Processing fileChoix-081.jpg
Processing fileChoix-013.jpg
Processing fileChoix-117.jpg
Processing fileChoix-024.jpg
Processing fileChoix-010.jpg
Processing fileChoix-043.jpg
Processing fileChoix-027.jpg
Processing fileChoix-118.jpg
Processing fileChoix-011.jpg
Processing fileChoix-087.jpg
Processing fileChoix-055.jpg
Processing fileChoix-123.jpg
Processing fileChoix-099.jpg
Processing fileChoix-084.jpg
Processing fileChoix-001.jpg
Processing fileChoix-090.jpg
Processing fileChoix-078.jpg
Processing fileChoix-021.jpg
Processing fileChoix-046.jpg
Processing fileChoix-089.jpg
Processing fileChoix-095.jpg
Processing fileChoix-063.jpg
Processing fileChoix-106.jpg
Processing fileChoix-060.jpg
Processing fileChoix-023.jpg
Processing fileChoix-109.jpg
Processing fileChoix-056.jpg
Processing fileChoix-111.jpg
Processing fileChoix-086.jpg
Processing fileChoix-009.jpg
Processing fileChoix-124.jpg
Sanitizing tree...

Using Ubuntu 20.04 and latest Calibre

**Comment by pavelzw** [comment]
This is the same problem as #4.

**Comment by ali-oem** [comment]
> This is the same problem as #4.

And the solution ?

**Comment by pavelzw** [comment]
Is discussed there: @Hex007 will submit a bug fix soon and it will be fixed in the next release.
